name: in_app_configs
description: "Configs is a powerful environment-aware configuration manager for Flutter apps."
version: 1.0.1
repository: https://github.com/Mohiuddin655-PUB/in_app_configs

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_remote: ^1.0.1
  object_finder: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0